name: movie_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  logger:
    path: logger

  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  better_player_plus: ^1.0.8
  floating: ^6.0.0
  video_player: 2.9.3
  chewie: 1.11.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  go_router: ^14.8.1
  dio: ^5.8.0+1
  dartz: ^0.10.1
  get_it: ^8.0.3
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.3.0
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  sqflite: ^2.4.2
  flutter_cache_manager: ^3.4.1
  html_unescape: ^2.0.0
  flutter_vlc_player: ^7.4.3
  flick_video_player: ^0.9.0
  pod_player: ^0.2.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/avatar/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700
