// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOjKFvPV42310fjKe4jmEHkprV3FIcWRw',
    appId: '1:280901368675:web:72b85822af3eaadb2ab156',
    messagingSenderId: '280901368675',
    projectId: 'movie-app-flutter-d070c',
    authDomain: 'movie-app-flutter-d070c.firebaseapp.com',
    storageBucket: 'movie-app-flutter-d070c.firebasestorage.app',
    measurementId: 'G-ZELC669E56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmXTrI7JcHrhk-LgA01_NLWhz0M8SAGx8',
    appId: '1:280901368675:android:959d890310f262652ab156',
    messagingSenderId: '280901368675',
    projectId: 'movie-app-flutter-d070c',
    storageBucket: 'movie-app-flutter-d070c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxX7K7_AzayMh10jsr4vzE35bwS_2BdLE',
    appId: '1:280901368675:ios:73880a1964ab0ef32ab156',
    messagingSenderId: '280901368675',
    projectId: 'movie-app-flutter-d070c',
    storageBucket: 'movie-app-flutter-d070c.firebasestorage.app',
    androidClientId: '280901368675-8f534k430iub3v5mgg9s3m06qme0kdbb.apps.googleusercontent.com',
    iosClientId: '280901368675-8m65iqr9v90ggjckiepo8e8f0p400fql.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxX7K7_AzayMh10jsr4vzE35bwS_2BdLE',
    appId: '1:280901368675:ios:73880a1964ab0ef32ab156',
    messagingSenderId: '280901368675',
    projectId: 'movie-app-flutter-d070c',
    storageBucket: 'movie-app-flutter-d070c.firebasestorage.app',
    androidClientId: '280901368675-8f534k430iub3v5mgg9s3m06qme0kdbb.apps.googleusercontent.com',
    iosClientId: '280901368675-8m65iqr9v90ggjckiepo8e8f0p400fql.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOjKFvPV42310fjKe4jmEHkprV3FIcWRw',
    appId: '1:280901368675:web:6198e6984487d37c2ab156',
    messagingSenderId: '280901368675',
    projectId: 'movie-app-flutter-d070c',
    authDomain: 'movie-app-flutter-d070c.firebaseapp.com',
    storageBucket: 'movie-app-flutter-d070c.firebasestorage.app',
    measurementId: 'G-8R5JB60MWY',
  );
}
